# Generated by Django 3.1.7 on 2022-08-17 11:29

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0004_registeredvoters_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='VotersModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('choice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choice', to='accounts.registeredvoters')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_by', to='accounts.registeredvoters')),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_at', to='accounts.department')),
                ('year', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='voters_year', to='accounts.year')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='VoteModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.BooleanField(default=True)),
                ('end', models.BooleanField(default=False)),
                ('department', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vote_department', to='accounts.department')),
                ('year', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vote_year', to='accounts.year')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
