# Generated by Django 3.1.7 on 2022-08-17 11:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20220817_1129'),
        ('vote', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='votemodel',
            options={'ordering': ('department',)},
        ),
        migrations.AlterModelOptions(
            name='votersmodel',
            options={'ordering': ('department',)},
        ),
        migrations.AlterField(
            model_name='votemodel',
            name='department',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='vote_department', to='accounts.department'),
        ),
    ]
