# Generated by Django 3.1.7 on 2022-08-17 11:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20220817_1129'),
        ('vote', '0002_auto_20220817_1148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='votemodel',
            name='department',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vote_department', to='accounts.department'),
        ),
    ]
