# Generated by Django 3.1.7 on 2022-08-17 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0003_auto_20220817_1148'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VoteModel',
        ),
    ]
