# Generated by Django 3.1.7 on 2022-08-18 00:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20220817_1129'),
        ('vote', '0004_delete_votemodel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='votersmodel',
            options={},
        ),
        migrations.CreateModel(
            name='VoteModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.BooleanField(default=True)),
                ('end', models.BooleanField(default=False)),
                ('department', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vote_department', to='accounts.department')),
                ('year', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vote_year', to='accounts.year')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
