# Generated by Django 3.1.7 on 2022-08-25 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0005_auto_20220818_0055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='votemodel',
            name='start',
            field=models.BooleanField(default=False),
        ),
    ]
