# Generated by Django 3.1.7 on 2022-08-17 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20220731_1217'),
    ]

    operations = [
        migrations.AddField(
            model_name='registeredvoters',
            name='password',
            field=models.CharField(default='33', max_length=255),
        ),
    ]
