# Generated by Django 3.1.7 on 2022-08-17 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_registeredvoters_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registeredvoters',
            name='password',
            field=models.CharField(max_length=255),
        ),
    ]
