# Generated by Django 3.1.7 on 2022-08-24 23:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20220817_1129'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registeredvoters',
            name='password',
        ),
        migrations.RemoveField(
            model_name='registeredvoters',
            name='verified_voter',
        ),
    ]
