# Generated by Django 3.1.7 on 2022-08-25 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20220824_2310'),
    ]

    operations = [
        migrations.AddField(
            model_name='registeredvoters',
            name='verified_aspirant',
            field=models.BooleanField(default=False),
        ),
    ]
