# Generated by Django 3.1.7 on 2022-08-26 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20220825_2157'),
    ]

    operations = [
        migrations.AddField(
            model_name='registeredvoters',
            name='point',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
