# Generated by Django 3.1.7 on 2022-08-27 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_registeredvoters_point'),
    ]

    operations = [
        migrations.AddField(
            model_name='aspirantposition',
            name='level',
            field=models.CharField(choices=[('nd', 'nd'), ('hnd', 'hnd')], default='nd', max_length=50),
        ),
        migrations.AddField(
            model_name='registeredvoters',
            name='level',
            field=models.CharField(choices=[('nd', 'nd'), ('hnd', 'hnd')], default='nd', max_length=50),
        ),
    ]
